### ISSUE TITLE
aio is not real asynchronous file IO

### ISSUE THREAD

**Issue by TitanSnow** [mosquito/aiofile#10]
aio — POSIX asynchronous IO, which is used by this package aiofile — is **not real** asynchronous file IO. You could find these sentences in manpage (`man 7 aio`):

> The current Linux POSIX AIO implementation is provided in user space by glibc. This has a number of limitations, most notably that maintaining multiple threads to perform I/O operations is expensive and scales poorly.

It’s just based on user‐space threads, which is not different from simply using ThreadPool to read file in Python.

**Comment by mosquito** [comment]
1. It's correct for the **glibc** implementation (e.g. [OpenBSD has no this limitation](https://man.openbsd.org/NetBSD-7.1/aio.3))
2. The OS provide asynchronous file IO functions and this library just provides Python API.
