### ISSUE TITLE
AttributeError: 'AIOFile' object has no attribute 'flush'

### ISSUE THREAD

**Issue by hsh-dhts** [mosquito/aiofile#11]
It raise AttributeError: 'AIOFile' object has no attribute 'flush',when I run the code example in win10,python3.6
why?

**Comment by mosquito** [comment]
Actually the `flush` is a little bit wrong name for the function. The flushing operation makes after each read and write operation. This method was renamed as fsync (because this does fsync actually). I forget change a Redame.md it's my mistake. Now it's actual. Thank you for report.
