### ISSUE TITLE
AioFile should supports wave library

### ISSUE THREAD

**Issue by satels** [mosquito/aiofile#28]
We are using Yandex Cloud Speech and are using lpcm codec especially.

https://cloud.yandex.ru/docs/speechkit/tts/request

There is code for the one from the example:

```python
with wave.open(test_filepath, 'wb') as file_obj:
    file_obj.setparams((1, 2, 8000, 0, 'NONE', 'NONE'))
    file_obj.writeframes(content)
```

Can you manage to support wave lib?

For instance, like this:
```python
async with AIOWaveFile("/tmp/test.wav", 'wb') as afp:
        await afp.setparams((1, 2, 8000, 0, 'NONE', 'NONE'))
        await afp.write(content)
        await afp.fsync()
```

**Comment by mosquito** [comment]
The library mission is provide the simplest way to read and write any kind of file asynchronously. Of course you fell free to wrap it in your custom class for making wav files.
