### ISSUE TITLE
Wheel for Python 3.8

### ISSUE THREAD

**Issue by Mulugruntz** [mosquito/aiofile#31]
Hi,

Could you please add support for Python 3.8? Including the wheel?

Thanks in advance,
Samuel

**Comment by Mattwmaster58** [comment]
Just curious, why do you want a wheel?

**Comment by mosquito** [comment]
Since [aiofile>=2.0.0](https://pypi.org/project/aiofile) is using [caio](https://pypi.org/project/caio). The Linux and macOS wheels are now available for caio.
