### ISSUE TITLE
os.pwrite() on windows !!

### ISSUE THREAD

**Issue by dinihou** [mosquito/aiofile#39]
Hi
today AIOFile stop working and throw this exception (install from pip on venv)

> 
> ERROR      05:07:03 __eml:162 fetch module 'os' has no attribute 'pwrite'
> Traceback (most recent call last):
>   File "c:\xxx\pyimap\v.1.2\export\__eml.py", line 150, in fetch
>     await afp.write(_eml)
>   File "C:\xxx\pyimap\v.1.2\venv\lib\site-packages\aiofile\aio.py", line 219, in write
>     return await self.__context.write(bytes_data, self.__fileno, offset)
>   File "C:\xxx\pyimap\v.1.2\venv\lib\site-packages\caio\asyncio_base.py", line 88, in submit
>     return op.get_value()
>   File "C:\xxx\pyimap\v.1.2\venv\lib\site-packages\caio\python_aio.py", line 188, in get_value
>     raise self.exception
>   File "C:\xxx\pyimap\v.1.2\venv\lib\site-packages\caio\python_aio.py", line 71, in _in_thread
>     result = op_map[operation.opcode](operation)
>   File "C:\xxx\pyimap\v.1.2\venv\lib\site-packages\caio\python_aio.py", line 39, in _handle_write
>     return os.pwrite(
> AttributeError: module 'os' has no attribute 'pwrite'

**Comment by mosquito** [comment]
fixed on caio==0.5.2
