### ISSUE TITLE
"@coroutine" decorator is deprecated since Python 3.8

### ISSUE THREAD

**Issue by colidyre** [mosquito/aiofile#41]
When I test my program using aiofiles==0.5.0 (latest available version) with pytest in Python 3.8.0, I get the following warning:

```
[...]/lib/python3.8/site-packages/aiofiles/os.py:10: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def run(*args, loop=None, executor=None, **kwargs):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
This is similar to e.g. [this issue](https://github.com/aio-libs/aioredis/issues/648), where also this information is probably helpful for this repo:

[Python 3.5 Documentation](https://docs.python.org/3.5/library/asyncio-task.html#coroutines):

> The async def type of coroutine was added in Python 3.5, and is recommended if there is no need to support older Python versions.

**Comment by mosquito** [comment]
Wrong repo, this module is `aiofile` it's not the aiofile**s**

**Comment by colidyre** [comment]
Oh, I'm sorry for the inconvenience.
