### ISSUE TITLE
Examples for writing large files in append mode

### ISSUE THREAD

**Issue by rajdeeprath** [mosquito/aiofile#44]
Hello,

Thank you very much for your hard work on this. I am testing things with **aiofile** to see if i can write a large file (might go up to 400-500mb) from a continuous data stream in append mode. I can't seem to find an example of writing a large file in append mode using **aiofile** in **pypi** or **readme**. Can you please point me to an example?

**Comment by mosquito** [comment]
https://github.com/mosquito/aiofile#write-and-read-with-helpers <https://github.com/mosquito/aiofile#write-and-read-with-helpers> this example should work as well. If you want to write binary data you use "wb" mode.
