### ISSUE TITLE
Example async_open-helper misses to do seek before readLine

### ISSUE THREAD

**Issue by PrabhuJoseph** [mosquito/aiofile#51]
https://github.com/mosquito/aiofile/blob/master/README.rst#async_open-helper misses to do seek before readLine. Have added "afp.seek(0)" in below code snippet.

{code}
      await afp.write("Hello from\nasync world")
       >> afp.seek(0) << 
        print(await afp.readline())
        print(await afp.readline())
{code}

**Comment by mosquito** [comment]
Nah, the `README.rst` is testing with pytest.
