### ISSUE TITLE
Can't install on Amazon Linux

### ISSUE THREAD

**Issue by ReyanshKharga** [mosquito/aiofile#57]
I get the following error. 

`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.7m -c caio/thread_aio.c -o build/temp.linux-x86_64-3.7/caio/thread_aio.o -g
    caio/thread_aio.c:6:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1`

**Comment by mosquito** [comment]
You have to install python’s headers, otherwise  any packages with c extensions will throw this error.

**Comment by ReyanshKharga** [comment]
Thanks
