### ISSUE TITLE
Async csv.DictReader

### ISSUE THREAD

**Issue by Natim** [mosquito/aiofile#6]
DictReader can take any iterator that defines `__next__` but no async generator.

it would be great to create an `aiofile.DictReader` for that.

Here is the [workaround](https://mail.python.org/pipermail/python-dev/2017-March/147558.html):

    import csv
    import io

    raw_bytes = await stream.read(10000000)
    wrapped_bytes = io.BytesIO(raw_bytes)
    text = io.TextIOWrapper(wrapped_bytes, encoding=encoding, errors='replace')

    for i, row in enumerate(csv.DictReader(text)):
        print(row)

**Comment by mosquito** [comment]
[Another one example](https://github.com/mosquito/aiofile#async-csv-dict-reader) for this issue

**Comment by mosquito** [comment]
This code is just an example. This is just an illustration of the principle and should be used only if you fully understand the risk.
