### ISSUE TITLE
Add support for StringIO and BytesIO

### ISSUE THREAD

**Issue by skrech** [mosquito/aiofile#65]
Hello, 
Thanks for the great package!

I want to make a feature request for adding support for aiofile's equivalent of StringIO and BytesIO from the standard python lib. These will be particularly useful when writing test, as test doubles. Currently, the only way to test functions that use aiofile is to create temporary files and wrap them in AIOFile.

**Comment by mosquito** [comment]
There are several reasons why you should never do this:
1. StringIO and BytesIO are an abstraction over memory, and there is no benefit to doing memory operations asynchronously.
2. This library is designed to work with files through streams or through the kernel mechanism, if you want to do a functional test, it's most logical to do it through temporary files.

You can implement your own pseudo-context by deriving it from the `AsyncioContextBase` class and doing everything over SringIO or BytesIO already in it.
