### ISSUE TITLE
Missing posix_aio.c

### ISSUE THREAD

**Issue by rendaw** [mosquito/aiofile#8]
Installing via the git repository fails due to the above missing file.  AFAICT it's not in the repository.

I just realized 0.5.2 is on pypi but it would be nice to have this as a backup.

**Comment by Natim** [comment]
Have you tried installing libaio-dev?

    $ sudo apt install libaio-dev

**Comment by rendaw** [comment]
Thanks!  I have that installed.

```
$ pacman -Ql libaio
libaio /usr/
libaio /usr/include/
libaio /usr/include/libaio.h
libaio /usr/lib/
libaio /usr/lib/libaio.so
libaio /usr/lib/libaio.so.1
libaio /usr/lib/libaio.so.1.0.1
```

I think that's roughly what's included in the Debian/Ubuntu package.

**Comment by daskol** [comment]
@rendaw you are needed `cython` to be installed. Look at [this line](https://github.com/mosquito/aiofile/blob/master/setup.py#L27) of extension building script.

By the way, it is quiete suspiciously that `core/libaio` installation solved your problem. The reason is that `aiofile` uses `aio.h` header directly that is part of `librt` shipped with `core/glibc`.

**Comment by rendaw** [comment]
Thanks @daskol - that was the issue.  Is the except block non-functional then?  Leaving this open in case the posix_aio.c file should be added so the except block works, or in case the try block should log an error about Cython and abort the build if Cython is a hard requirement.

**Comment by daskol** [comment]
@rendaw No, except block is actual fallback in case of source distribution(sdist). Agreed. There is a lack of documentation. I believe @mosquito adds something on it into `README`.

**Comment by rendaw** [comment]
I have nothing further useful to add to this ticket but I want to thank you for making this awesome project.

**Comment by mosquito** [comment]
Thank you.
