### ISSUE TITLE
No flush API and no way to set unbuffered writes in binary mode

### ISSUE THREAD

**Issue by ustulation** [mosquito/aiofile#84]
## Long story short

Correct me if wrong but the way I think the file writing works is that the contents first accumulate in the user-space buffer(s) (application/standard-lib buffer) which is either periodically (on size threshold) or explicitly (using `flush`) flushed to the OS buffers (kernel space buffers). Then when `fsync` is called, the OS persists whatever is in its kernel space buffer(s) to the disc (for the given file handle).

In binary mode one could set the writes as being unbuffered, meaning we don't have to call `flush` and can directly call `fsync` after a write if desired. In text mode we cannot set it as unbuffered so we need to explicitly call `flush` to submit to OS buffer.

I neither see a way to disable buffering for writes nor do i see a `flush` function anywhere. Calling `fsync` without `flush` could in theory not write everything that was expected (only that which was submitted to OS buffer) unless the mode was unbuffered.

Could you please let me know how to:
1. Set unbuffered flag for writes
2. Call `flush` explicitly for both binary and text modes
?

**Comment by mosquito** [comment]
The asynchronous linux API has no text mode it working only in binary modes. In a given library, anything that can open, [under the hood](https://github.com/mosquito/caio/blob/master/caio/linux_aio.pyi#L20), is written in binary mode, encoding and decoding bytes each operation.

**Comment by ustulation** [comment]
Ah right, good to know thanks. OK in that case let's forget about the text mode. The two points that i mentioned should still be valid? An explicit `flush` API to flush user-space buffer to kernel-space and a parameter/API to set the buffering to `unbuffered` (in which case the `flush` won't be necessary) should exist for binary I/O. Without those there's a good chance of ordering violation.

Eg. the application writes data followed by checkpoint, the checkpoint made it to kernel space buffer and was written but the OS crashed before the data ever made it through to the kernel-space buffer. Now on resumption the application will see the checkpoint and incorrectly assume things and skip over processing the input which leads to creation of the data resulting in a data-loss. With proper flush mechanism (or if users don't care about periodic flushing and set writes to be unbuffered) the sequence could be:
1. Writer the data
2. `flush` the data (or skip this if unbuffered)
3. `fsync` it
4. write the checkpoint (and optionally flush + fsync it. Checkpoint not making it through just means repeated work/duplicated data if things crash, but there's no data-loss which might be more important to some).

**Comment by ustulation** [comment]
Covered in https://github.com/mosquito/aiofile/pull/85.
